### PR TITLE
Spect 260

### PR DESCRIPTION
**Pull request by dy**
- clear/trim shortcut
- fixed tail skipping overshoot on identical input/output arrays
- size bumped to 260 (+8b)

### CODE REVIEW

**Comment by WebReflection** [comment]
this looks good to me, but if you find situations that could make some implementation fail, maybe we should add that test too, probably as part of the warm-up/generic checks with assertions?

**Comment by dy** [comment]
@WebReflection sure, just simple identity transform check:
```js
diff(container, [...childNodes], [...childNodes], before);
```
It did not fail, but created overshoot.

Another possible test cases I found - 
```js
// one in the middle
diff(container, [...childNodes], [...childNodes.slice(0, 2), createNode(0), ...childNodes.slice(3)], before)

// ring
diff(container, [...childNodes], [...childNodes.slice(1), childNodes[0]], before)

// swap tail
diff(container, [...childNodes], [...childNodes.slice(-1), childNodes.slice(1,-1), childNodes[0]], before)

// trim
diff(container, [...childNodes], childNodes.slice(1, -1))
```

**Comment by dy** [comment]
Tbh I don't follow the logic of benchmark. Should that be a separate util method for each of the test cases?

**Comment by dy** [comment]
Ok, just checked libs in spect test suite - snabbdom is broken on prepend #39, all other libs pass all tests except for _live input nodes_ (input array cannot be directly _parent.childNodes_).
If you have an idea how to properly organize tests here - let's do that in a separate PR.

**Pull request merged**
