### PR TITLE
Add 191 bytes implementation

### PR DESCRIPTION
**Pull request by dy**
191 bytes spect with better memory/performance profile, deflate-first strategy.

### CODE REVIEW

**Comment by WebReflection** [comment]
This is interesting, but I wonder at this point if you really need two sets, when `array.includes` works the same as `set.has`, the `array.push` works faster than `set.add`, as no validation is needed, and you wouldn't even need to `new Set(b)`.

However, if you're happy with the two sets, I'm happy to merge this.

**Comment by WebReflection** [comment]
Example of how I'd write it:

```js
module.exports = (parent, a, b, end = null) => {
  let aidx = [], i = 0, cur, next, bi

  while (bi = a[i++]) b.includes(bi) ? (aidx.push(bi), cur = cur || bi) : parent.removeChild(bi)
  cur = cur || end, i = 0

  while (bi = b[i++]) {
    next = cur.nextSibling

    // skip
    if (cur == bi) cur = next

    else {
      // swap
      if (b[i] === next && aidx.includes(bi)) cur = next

      // insert
      parent.insertBefore(bi, cur)
    }
  }

  return b
}
```

**Comment by WebReflection** [comment]
P.S. either ways, accessing an out of bound index would forever de-optimize the array. The entry array `a` can probably be de-optimized without issues, but I'd really consider using the `b.length` instead of looping via `b[i++]`, as the `b` is the array that you return, and the faster it works, the better.

**Comment by dy** [comment]
I noticed that `a.includes` or `b.includes` performs poorly on 10k swap/create, compared to set.
One ridiculous discovery though is that `aidx` is not needed, so it allowed reducing size to 177b with better performance/memory. The gained space can be used for append-only shortcut (prominent case!), but I wonder if there's a way to generalize it.

**Comment by dy** [comment]
Ok, switched to no-sets inflate-first strategy (that turns out to be even more compact - 168bytes), but added fast shortcuts for the saved space. Now 215b, but performs better.

**Comment by WebReflection** [comment]
this is actually how I would write this:

```js
module.exports = (parent, a, b, end = null) => {
  let aLength = a.length, bLength = b.length, i = 0, cur, next;
  while (i < aLength && i < bLength && a[i] === b[i]) i++;
  if (i == aLength)
    while (i < bLength)
      parent.insertBefore(b[i++], end);
  else {
    // in no circumstances a[i] can be falsy here
    cur = a[i];
    while (i < bLength) {
      // is bi = b[i++] really needed?
      next = cur ? cur.nextSibling : end;
      if (cur == b[i++])
        cur = next;
      else if (i < bLength && b[i] == next) {
        parent.replaceChild(b[i-1], cur);
        cur = next;
      }
      else
        parent.insertBefore(b[i-1], cur);
    }
    while (cur != end) {
      // in no circumstances `cur` can be falsy here ...
      next = cur.nextSibling || end;
      // ... or this would've failed, if `cur` was falsy
      parent.removeChild(cur);
      cur = next;
    }
  }
};
```

**Pull request merged**
