### PR TITLE
Add 225b spect impl

### PR DESCRIPTION
**Pull request by dy**
This creates 225b spect implementation:

image

@luwes @WebReflection please consider.

### CODE REVIEW

**Comment by dy** [comment]
Ty 🙏 !

**Comment by luwes** [comment]
the performance is a lot worse on my computer it seems. spect is almost always last or second last.

Screen Shot 2020-04-17 at 7 38 22 PM

**Comment by luwes** [comment]
on Mac 10.15.4, 2.3 GHz 8-Core Intel Core i9, Node v13.8.0

**Comment by dy** [comment]
Sets − I suppose their implementation varies across platform/node version.
Just `nvm`-ed node to `13.12.0` and there:
image

**Comment by dy** [comment]
That seems to be system culprit. With _create 15k_ and more nodes spect demonstrates stable smallest time:
image

**Pull request merged**
